### ISSUE TITLE
Create Roadmap

### ISSUE THREAD

**Issue by Shieka** [hpi-swa-teaching/Liquid#34]

**Comment by Dassderdie** [comment]
**Outdated:**

As a host, I want to run the same poll multiple times, so I don't need to type it out again and again.

In multi-question surveys, I want to be able to see a recap of all of my answers after the last question, and be able to go back to a specific question to change my answer, without having to restart the survey.

As a host, I want to run prioritisation polls, so I can e.g. run complex votes.

As a host, I want to run free-text polls, so I can collect ideas & feedback.

As a host, I want to run multiple-choice polls, so I can e.g. run popularity votes.

As a host, I want to be able to choose whether or not participants can see the poll results, so I can create polls where the results are only meant for internal use.

As a poll participant, I want to get a clear idea of the poll's characteristics (number of votes allowed / who can see the results / ...), so I don't make mistakes during voting.

As a host, I want to have a visualization of the results, so I can easily evaluate the answers.

As a host, I want to prepare polls to be held at a later time, so I don't need to copy and paste from a text file all the time.

As a host as well as a participant, I want to be able to see my poll history, so I can look at results at a later time and easily compare polls from within Liquid.

**Maybe already done:**

As a host, I want to be able to ask multiple questions in one poll, so I can ask more specific questions instead of one generalised one, as well as make the process easier for my participants.

**Comment by Dassderdie** [comment]
![Roadmap Liquid](https://user-images.githubusercontent.com/18506183/119369351-5ae4a080-bcb4-11eb-9216-a245b2479aeb.png)

**Comment by Dassderdie** [comment]
https://lucid.app/lucidchart/invitations/accept/inv_254ec194-a68f-4bc8-b621-bd25e241b9f1?viewport_loc=1463%2C-277%2C157%2C55%2C0_0
