### ISSUE TITLE
Add ifError:-Handler to RemoteRepoClient

### ISSUE THREAD

**Issue by Skn0tt** [hpi-swa-teaching/Liquid#97]

**Comment by Dassderdie** [comment]
As we briefly discussed before lunch:
@richardschiemenz  and I think it doesn't make a lot of sense to implement this, because Squeak already shows an error window if this happens and a custom window wouldn't really improve the UX for the Squeak-User (who is arguably already familiar with this error experience from the rest of the ui -> the current solution is native to the Squeak environment).
